### ISSUE TITLE
Room name

### ISSUE THREAD

**Issue by iFac3** [beele/HomebridgeUnifiProtectMotion#2]
Hi! Thanks for this plugin!

I have a question. Do I need make configs for all the rooms where I have UVC installed?

**Comment by beele** [comment]
No a single config will do fine. 
The room name in the config is where all the motion sensors will be placed initially. It's where the "platform" is.
You can move each motion sensor to the room it needs to be from within the Home app.

**Comment by iFac3** [comment]
Thanks! Works like a charm! ;)
