### ISSUE TITLE
Rich notifications no longer work as of iOS 13.x

### ISSUE THREAD

**Issue by BadgerBadgerAndFox** [beele/HomebridgeUnifiProtectMotion#6]
Confirmed as not working on iOS 13.1 Beta 4

I'm feeding 5 cameras from Unifi Protect using "homebridge-unifi-protect2".
Motion sensors for the Unifi cameras are provided by "homebridge-unifi-protect-motion-sensors".

I'm also running 1 camera in "homebridge-camera-ffmpeg" with the RTSP feed from Synology Surveillance Station.
Motion sensor is provided from "homebridge-sss-platform".

Homebridge is running in Docker container from oznu/homebridge on the Synology DiskStation.

Each camera has the same display name as the associated motion sensor and is located in the same room in HomeKit, and as with others the rich notifications worked prior to iOS 13.x

@beele  Let me know if there is anything else i can provide to assist. Other Homebridge users have reported the same issue in iOS 13.x for "homebridge-camera-ffmpeg" https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/332

**Comment by beele** [comment]
I'm having the same problem since ios 13, no solution for now.
AFAIK it's an issue with ios 13 :/

**Comment by BadgerBadgerAndFox** [comment]
This has been resolved via an update to homebridge-camera-ffmpeg, requires the fix to also be implemented in homebridge-unifi-protect2 though. I have manually merged the code on my install to get it working.
